language: java
sudo: false
install: true

addons:
   sonarcloud:
   organization: "travistest"
   token:
      secure: "Ik05dE8VzWTYhI1GiGuAp00Eh+VjSozemM7TDVTHXeIp2UhYK5DAfjMUXFf2OwE3pXDoO7IeuJkZXC8gw2IYWzCaK5/uoJ5dsKTeFv3CRqJUO4gQFlisPVPOwP94zgwmRY091msU/IiMHKUMGAKAuq6JeVFiLf2BD9tsDzx1dwQY4SOgoLoefJtmWuFZRt+13SwkHYMNtZet82JPlEVzBrjNcHDU8yLYQUSbADgDcBjkuh1FW4aeWvXp5kJUQ2hD9gpAIUTwlIGJn+wc2uKmxA2zm8136aK/qjIfYvkhZIadWBTQFCOd/f3jot50LJWkwbhy2687Op07oEvVqvklJF59Nt8q2zuIlD5hzxy5F0aox8xE8eFjK5zj5fWpGRwU/F3YtxWNqlSe2ygYgvs5ps1qAcszV4btkiWuO29iFdzehRH3auseheQPZi+FJnWtiChdGj1oQIRpsLdq/qcJrBTDu8CFwc6812j9YaMt6eF5MNKbPgRRxB7RJ7GbDxk4iv7xcwQPJx2PG+LxqWEaXfxe5vglRYfpATnoSdpbG0OOkhEP/eMlnsSfShe2sTp9affE9PQE9JVjvhe/FpOZbjedSsjlpEpQ1P0ORSZ7AasELfV1yuZgV+g21dE9/Jaady3FcEab1Op5Qp4kM5NP6K5q2t++BqvauFtu0kmMtAg="
jdk:
   - oraclejdk8
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
