language: java
jdk: openjdk8
script: ant build
dd:
  secure: BMeiFdYBi9XSflHpOblLbwLfv+cLpcRx4TylRFkp8Z+VC0xrsfvhkVr6ThvzDUyRE1gQiK3GrS3NJUIOOz/KpOjEvja3T29wzSVgETP48T4AQ3FF6UUVqIJzSdcFjH93cCGT3ArVfs2vkfbtJEfPgU390INVvuk1XC7RACC7jD9dyhaRvou+M71YsQI+DEGaLHhUXhrL4DQbF0lEyQLYyDvY5WdlMnArHyPRAEuWL+T+FDfEldBjr8nRCEkHmHMTKUMlens/cNJxEF2hDlNryc5DHSF8Xj8m3bTm9ujqNos4Ge/BrClnw3rAe5w1vaNBlhnBYr9dF5QVt10BGHbvLkIUWmIeIDk2CLhorzTl9+FWtkblBu3Zf53BJL0qxPazkv3ov4sbro61x9wnPerBIwTr7/kbKgXkfSZE2bF25cUeoh+doZUw0NK+xIKyy0iKJXkr7c9ml2xnGc4hAGb7S16X8W26SPbFgbLqTFj9OAU4CGrQPGbF03u7FFTLBvi7lW9XUMDL46EzI6nT3KiB5+qtEVPfnW/sKIvciB5m98ZatjJPAsOa3Yc1BMAyk/40Agb9W2gSXvCMZVzPAr39D2IlsUHgPps/B+7muyyrBVS9K0aq2309kgNoYoDF6RJ0Etug4RHdBi2GECrsOzTJuV1U6sKUcboRSlrrfKZpFX4=
env:
  global:
   secure: SPC375DfzOgwadHvT8iZWucYzj6962i5jivUHJpl41keEicMebnqX7de3qDqDfQ43vuOvDKN9FPnuva22CshwSKMb3U1D+V2EfP1yD6Xd2A+TPe6XOgn/9OfIPPkqlsJgnVZZfH68gXgje9O3MuSn3zrZ2CsMFiGEIK0u5hKHQH3uVHZSyyO9kd2eOn/fbe8+MhWMDLUEK69Gr+MNh+RCmui+zkVqrjdPGbPu+loGmATei/+obs131ioYNyc6+eBj8XfhZX0u+XGAffxFcXEx3cejdERDz4Lpb4RJJrYJ5CfrQ3pGT8eHx8GmZM6IdyvsLYr8Exsn5CX9iYe+GceSa/SN/et68tzh7230VhYsi/QPVlSlApNV0XCJntDFWgZ21a8UFMI4DAG75L8Yg5AGVkOsQcPfRPOsiiWi/tvTj1fQ3dOEfCc1pTeosDMxi/Fz9IOfwG3hyUh6cPhOhbCjv6ZHHpMkYyPn/fSP6Kjpn4bu2/BSfutnVJ+UuY1mqMOjK76uHEVlQXIQzgKXRviU1o+eXVkW3tz5uEmzVYPDVtLOwwHTZwgIvmhSBlYUGj97OIJs15ZN0322+8bwJ96oB1s2AA2YCUbTxtojyT8L7UbN/Hm/oSOZgzNj4nzXhC4xDOf+w3+s9u2IteX0mtAy4m3d8Mf0m/O6x1PtbZ/cks=

addons:
   sonarcloud:
   organization: "continuous-integration" # the key of the org you chose at step #3
script:
   # other script steps might be done before running the actual analysis
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
