language: java
sudo: false
install: true

addons:
   sonarcloud:
   organization: "continuous-integration"
   token:
      secure: "kLApg7DVLPj436SClInxMe4sTbjc81i/LSiVs/530qwtThAVpq63sBuLiczeuQegloN2A1bUzQb8KEAgXmqXH77jIqTmHc+U/6i7WjyTx7xO+EV+tW15R8CYFhlgJIoqSH0YO9cIPSc2cRHMQntBSFziHJomjWKZX3RgzSl1IafQLhp7kZQS1UGBHCx2Ov4NeTOgwXImC0woBKCInTy9ZZefjooMfVQCmmeyJY8SuY7hFBBT7sCLyCPkJWnUyrvFuvi9dG53IFytXxQzZfmVQSfadLKD5DZj8LqPJk9SHLWoivX82zVzJKL0C/pd964HFELqN6jkTZ39zvyxlfJTuTC6KJ3NAFi4MlTfuHuXc+nlML/Rb6B9G8MtIzeiCfT8oyS+n17N41GVlThoWI+xxe30nPHhcaSWmkcb4D/KqUn815w4n1/5gqAJx8KrSSE1zNtNhp+Gcpjax0+fFJhkqM5GZwzUPcNyGXqjT8TbRHUwJy7Vi1xu7GZlojQc1m6M7ZLLKxAqopDDhIkQdA7fbOQtixNj9UO8ryatMOxTdv3kB9fixrrHsnt0wemBNtN5Qa53ZE6yU8stW3goR5MoWxfkl+Pd43cUB0w5/XpmvYcEhJSN7GU1FQ98t5tPC6icJVzU61I08QkLm2AlcSk/IIAZjpEyeDJ83tfe1Ix6d5g="
jdk:
   - oraclejdk8
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
