language: java
sudo: false
install: true

addons:
   sonarcloud:
   organization: nickpapadakis-github
   token:
      secure: G6kwAB/mjZm+FV80pzCvZbWd79RpPpCtaVPlaAh879XZ70j49SoGh/kqLfOYWwVAsyAJzEX4bcZELBe7f61H/LS3zBXxnUl2yY4RNGFVcQ6S6eVMxIBEuymUmFQHY0IccIOWV63hwSAe5WhdNlRG4ylIks4A7SkmqjoUz47x9pAoqkHRWMrkkJWBdszlDlBy7/NeWt4Jl/Fw8/q6n1seXLxpza/qN9ujD4vISsKUnTaNN6D1hNXPp7Jv60JNZNpSYky/C6U6dK8UsoRCJD4mPpOWHeAJOVjjFFO3G1jDrTOeRbbWf4YFw7/jckfZg/vYztfMi5mwQ3wEVc3aOFBvmtgw1p9tDdHqJ5wIhOxD3PJR4KZGWlUaNXltUkD1SNtQB02Xwestf3qZ1AlNjUrVGsdP/+0zs5o1OH4Yxwq8U9JK7NHLWVhI70uqu46qNmwBmi6XpyK2F0gWjVJIS96maW4ZeD5R5mmIzMxWPIsvCHBvbrHK2IGUeEB62H0Q7wEHY3cl8Xz4auSSxZyQq7gIx34TdHM5609l3lhc3AwTLqhMHuVoaHTJ3AFtEpDkli/Du0J5h0jPeToOHj/JJolVozsYr7OJYUyKHDS/wrjuew2MWOduUqfgsJlPFwN2VNRe1KkkB8AZL44I27mbAg95scFhujEb5bunZPEDgpOSJi8=
jdk:
   - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
