language: java
jdk: openjdk8
sudo: false
install: true

addons:
   sonarcloud:
   organization: "continuous-integration" # the key of the org you chose at step #3
   token:
      secure: "nwUnotgYDZLoYwws/WHzJobtrOxJ75alRzb6WpMtsphbo+I9YOTYijrXWF1W3dNHN1o/tsAadRd6nnuGlQ4KJUbByIIYfInH3VYke8qD0fG55qCUDNP7TEzIJMHtNDBpfeeGVxNFupgB7JIiCvLRgMyJtGx9ZSlzxwWxPldJ9k6c8OAxn78Sf+tOHRMD+ph0kWhRkXkJZ2d2BZgGHNKuJJBAb7Cq1JkFO8jgyB0ocLCsLbDClaTMs8xsOfrnO7lgJnAlEcL/jhe3KdKf2sYcdzwxO1av88z/rEpzM3stiLfDZc0KfQ1oPlHfi0msba86gsyFQDeY8Ry+v+cULn7J9F5cqrXcfmOJw8MCN9bnPq8npgjl1pZa0iHjyvByIc2bV83DuXxqwZfKp409W/37SYov3FaiLjgsJYxsfrlTpLbl1DXLm48bL2/ydFq8gEhLmiS63wgagOKjahA3s5iDbeSi5z8lUf4LfxxUBp0ZISBHJXimbk4w2Tg5F2cqcInFEbV6177xhDnHwhXg+srm414DZ0zEoCgB3VwPDGaGeoq2ZYQK+XlJeLEhJ/p6N4Ibw4jfWzv5BEZ0v5vg6ljSXpqdacfJld1gpKw65+TuJkQ8kwmID6tyINibtfEGsMYfC4ip3g8r5eb/PSoVin+GOslr1JLCyuel0EDIIh67h7s="
script:
   # other script steps might be done before running the actual analysis
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
