language: java
sudo: false
install: true

addons:
   sonarcloud:
   organization: "travistest"
   token:
      secure: "W3WFsalwBJ57SflYZVXF/xFLHpJzy6iZQt7Njrp1Stswnd6B4W5zwfUQ976cWDrpqm4DqrL3RUZBmbaJiZ2yDBp6vE+gjxPcmHp5IRn6JPH+V77SyHGdsrEZNdfLGuUe5VjgzcWeZ/qtZhzz1TgFKKcSM1uomaXm9M9QutHKEijuHFploSgYi78IZgRg44COWU3KxTqIzt3j0KdKonX7HoqP9KxSw+y7F0822Q4nvK3+LXgLbnhzJd1iZw+o//OP0a0JRm2o9TWd1oCNLksYhBLPPPa8khRCD41J2FtMgYTmunoinawgiBH/HrIAEZPt7K+kbrZ43p6dZBSALVcUvgC5gdJ6Tc+EvHCHd80Ypub3xHg/j5YZ55xRXfIaxDSMR1qc5BxXBNHAXU6/nnIJOwwgZh15DX4gFwD8o92ut5Yr1V03UXcSdRDqeEUC5jvWOLqthrPlbXL+mRS7er0f9xWdr6QYDZ0a+VDfoxyFV+/mKkRD2eFdpT+FW1NfwcbJHBkYlhWMuBt0IuiwbN2cVKfJyNDC0VEqjqKCKoZJFYxMwVfuLli79JkcLEWOhDHuUDuVGZcL52xWnZET5oIw9TrdLsHO9Ccws8fzxPyqlkcBJ7TadcjbXHuyaBm+JYJ19wgU0jHqPMnlSNVPMoUcstdwtw+Bq4z02bKL2GjY9VM="
jdk:
   - oraclejdk8
script:
   - mvn clean -e org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
